routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes([
    'reset' => false,
    'confirm' => false,
    'verify' => false,
]);
Route::get('/logout', 'Auth\LoginController@logout')->name('get-logout');

Route::group([
    'middleware' => 'auth',
    'namespace' => 'Profile',
], function () {
    Route::get('/profile', 'ProfileController@index')->name('profile');
    Route::get('/profile/ads/{category}', 'ProfileController@user_ads_by_category')->name('user_ads_by_category');

    Route::resource('ads', 'AdController')->except(['index', 'show']);
});

Route::get('/', 'MainController@index')->name('index');
Route::get('/how_is_it_made', 'MainController@how_is_it_made')->name('how_is_it_made');
Route::get('/obyavlenie', 'MainController@ads')->name('ads');
Route::get('/obyavlenie/{category}', 'MainController@ads_by_category')->name('ads_by_category');
Route::get('/obyavlenie/{category}/{ad_id}', 'MainController@ad_id')->name('ad_id');
Route::get('/user_ads/{user_id}', 'MainController@user_ads')->name('user_ads');

resources/views/ad.blade.php
@extends('layouts.master')
@section('title', 'Обьявление')
@section('content')
    {{--Все категорий, регионы и поиск--}}
    @include('layouts.search_form')

    <section id="all__ad" class="all__ad mt-4">
        <div class="container">
            <div class="row mb-3">
                <div class="ad__images col-lg-8">
                    <div class="main__image">
                        <img src="{{ Storage::url($ad->head_photo) }}" alt="" id="mainImage">
                    </div>
                    <div class="rest__images">
                        <button type="button" class="btn btn-outline-info m-1" onclick="switchImg('img/s1.jpg')"><img
                                src="img/s1.jpg" style="width: 100px;"></button>
                        <button type="button" class="btn btn-outline-info m-1" onclick="switchImg('img/s2.jpg')"><img
                                src="img/s2.jpg" style="width: 100px;"></button>
                        <button type="button" class="btn btn-outline-info m-1" onclick="switchImg('img/s3.jpg')"><img
                                src="img/s3.jpg" style="width: 100px;"></button>
                    </div>
                </div>
                <div class="ad__owner__address col-lg-4">
                    <div class="owner">
                        <div class="d-flex mb-2">
                            <i class="fa fa-user-circle fa-5x mr-2"></i>
                            <div>
                                <h4>{{$ad->owner_name}}</h4>
                                <a href="{{route('user_ads', [$owner->id])}}">Другие обьявления автора</a>
                                @isset($current_user)
                                    @if($owner->id == $current_user->id)
                                        <a class="btn btn-outline-secondary my-2" href="{{route('ads.edit', [$ad])}}">Редактировать объявление</a>
                                        <form action="{{route('ads.destroy', $ad)}}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <input type="submit" class="btn btn-outline-secondary" value="Удалить объявление">
                                        </form>
                                    @endif
                                @endisset
                            </div>
                        </div>
                        <div class="contacts mb-2">
                            <button onclick="showPhoneNum('ХЗ как это сделать')" type="button" class="btn btn-outline-info" id="show__num">
                                Показать номер
                            </button>
                            <button type="button" class="btn btn-outline-secondary">Написать атвору</button>
                        </div>
                    </div>
                    <div class="address">
                        <div class="d-flex">
                            <i class="fa fa-map-marker fa-2x mr-2"></i>
                            <p class="h5 font-weight-normal">{{$ad->address}}</p>
                        </div>
                        <iframe
                            src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d92988.42983572344!2d76.88355839999998!3d43.25376!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2skz!4v1597681934629!5m2!1sen!2skz"
                            width="350" height="330" frameborder="0" style="border:0;" allowfullscreen=""
                            aria-hidden="false" tabindex="0"></iframe>
                    </div>
                </div>
            </div>
            <div class="ad__description col-lg-8">
                @if($ad->isTop())
                    <span class="badge badge-warning">ТОП</span>
                @endif
                <div class="d-flex mb-3">
                    <p class="h4 font-weight-normal mr-auto">{{$ad->title}}</p>
                    <i class="fa fa-bookmark-o fa-2x mr-3"></i>
                    <i class="fa fa-share-alt fa-2x"></i>
                </div>
                <div>
                    <p class="h6 font-weight-normal mb-5">{{$ad->description}}</p>
                    <small class="text-muted mr-5">Опубликовано в {{$ad->created_at}}</small>
                    <small class="text-muted">Просмотры:820</small>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/ads.blade.php
@extends('layouts.master')
@section('title', 'Все обьявления')
@section('content')

    @include('layouts.search_form')

    <section id="last__ads" class="last__ads py-4">
        <p class="h3 font-weight-normal">
            @if(isset($category))
                Все обьявления по категорий: {{$category->name}} {{$category->ads->count()}}
            @else
                Все обьявления
            @endif
        </p>
        <div class="row justify-content-around">
            @foreach($ads as $ad)
                @include('layouts.ad_card')
            @endforeach
        </div>
    </section>
@endsection

resources/views/best_work_card.blade.php
<div class="card border border-info mb-lg-3" style="width: 17rem;">
    <img class="card-img-top" src="img/s1.jpg" alt="Card image cap">
    <div class="card-body">
        <div class="d-flex">
            <h5 class="card-title mr-auto">Card title</h5>
            <i class="fa fa-star-o fa-2x"></i>
        </div>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
            card's content.</p>
        <a href="#" class="stretched-link"></a>
    </div>
</div>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/how_is_it_made.blade.php
@extends('layouts.master')
@section('title', 'Как это сделано?')
@section('content')
    <section id="how__to" class="how__to py-4">
        <p class="h3 font-weight-normal">Как это сделано?</p>
        <div class="media border border-info p-2 rounded mb-2">
            <img class="media-left card-img" alt="Image" src="img/s1.jpg">
            <div class="media-body ml-2">
                <h4 class="card-title"><a href="#">Title</a> <span class="badge badge-info">Видео инструкция</span></h4>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente quasi tempore
                    vitae odit dignissimos ut ad voluptate. Excepturi et necessitatibus beatae, nobis placeat voluptas,
                    cupiditate, inventore consectetur neque eum cum voluptates nisi. Ab quia suscipit tempore inventore,
                    ex dolore, magni! ipsum dolor sit amet, consectetur adipisicing elit. Nemo rerum, harum sapiente
                    expedita nostrum et. Pariatur assumenda veritatis, aliquid qui.</p>
            </div>
        </div>
        <div class="media border border-info p-2 rounded mb-2">
            <img class="media-left card-img" alt="Image" src="img/s2.jpg">
            <div class="media-body ml-2">
                <h4 class="card-title"><a href="#">Title</a></h4>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente quasi tempore
                    vitae odit dignissimos ut ad voluptate. Excepturi et necessitatibus beatae, nobis placeat voluptas,
                    cupiditate, inventore consectetur neque eum cum voluptates nisi. Ab quia suscipit tempore inventore,
                    ex dolore, magni! ipsum dolor sit amet, consectetur adipisicing elit. Nemo rerum, harum sapiente
                    expedita nostrum et. Pariatur assumenda veritatis, aliquid qui.</p>
            </div>
        </div>
        <div class="media border border-info p-2 rounded mb-2">
            <img class="media-left card-img" alt="Image" src="img/s3.jpg">
            <div class="media-body ml-2">
                <h4 class="card-title"><a href="#">Title</a></h4>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente quasi tempore
                    vitae odit dignissimos ut ad voluptate. Excepturi et necessitatibus beatae, nobis placeat voluptas,
                    cupiditate, inventore consectetur neque eum cum voluptates nisi. Ab quia suscipit tempore inventore,
                    ex dolore, magni! ipsum dolor sit amet, consectetur adipisicing elit. Nemo rerum, harum sapiente
                    expedita nostrum et. Pariatur assumenda veritatis, aliquid qui.</p>
            </div>
        </div>
    </section>
@endsection

resources/views/index.blade.php
@extends('layouts.master')
@section('title', 'Главная страница')
@section('content')

    {{--Все категорий, регионы и поиск--}}
    @include('layouts.search_form')

    <section id="last__ads" class="last__ads py-4">
        <p class="h3 font-weight-normal">Последние обьявления</p>
        <div class="row justify-content-around">
            @foreach($ads as $ad)
                @include('layouts.ad_card', compact('ad'))
            @endforeach
        </div>
        <div class="d-flex justify-content-center">
            {{ $ads->links() }}
        </div>
    </section>

    <section id="best__works" class="best__works py-4">
        <p class="h3 font-weight-normal">Лучшие работы</p>
        <div class="row justify-content-around">

            <div class="card border border-info mb-lg-3" style="width: 17rem;">
                <img class="card-img-top" src="img/s3.jpg" alt="Card image cap">
                <div class="card-body">
                    <div class="d-flex">
                        <h5 class="card-title mr-auto">Card title</h5>
                        <i class="fa fa-star-o fMasmaa-2x"></i>
                    </div>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                        card's content.</p>
                    <a href="#" class="stretched-link"></a>
                </div>
            </div>
            <div class="card border border-info mb-lg-3" style="width: 17rem;">
                <img class="card-img-top" src="img/s1.jpg" alt="Card image cap">
                <div class="card-body">
                    <div class="d-flex">
                        <h5 class="card-title mr-auto">Card title</h5>
                        <i class="fa fa-star-o fa-2x"></i>
                    </div>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                        card's content.</p>
                    <a href="#" class="stretched-link"></a>
                </div>
            </div>
            <div class="card border border-info mb-lg-3" style="width: 17rem;">
                <img class="card-img-top" src="img/s3.jpg" alt="Card image cap">
                <div class="card-body">
                    <div class="d-flex">
                        <h5 class="card-title mr-auto">Card title</h5>
                        <i class="fa fa-star-o fa-2x"></i>
                    </div>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                        card's content.</p>
                    <a href="#" class="stretched-link"></a>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/user_ads_works.blade.php
@extends('layouts.master')
@section('title', 'User_name')
@section('content')
    <h2>{{$user->name}}</h2>
<nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <a class="nav-item nav-link active" id="nav-ads-tab" data-toggle="tab" href="#nav-ads" role="tab" aria-controls="nav-ads" aria-selected="true">Все объявления автора</a>
        <a class="nav-item nav-link" id="nav-works-tab" data-toggle="tab" href="#nav-works" role="tab" aria-controls="nav-works" aria-selected="false">Все работы автора</a>
        <a class="nav-item nav-link" id="nav-how_is_it_made-tab" data-toggle="tab" href="#nav-how_is_it_made" role="tab" aria-controls="nav-nav-how_is_it_made" aria-selected="false">Все работы автора по разделу "Как это сделано?"</a>
    </div>
</nav>
<div class="tab-content mt-3" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-ads" role="tabpanel" aria-labelledby="nav-ads-tab">
        <div class="row justify-content-around">
            @foreach($user_ads as $ad)
                @include('layouts.ad_card', compact('ad'))
            @endforeach
        </div>
    </div>
    <div class="tab-pane fade" id="nav-works" role="tabpanel" aria-labelledby="nav-works-tab">...</div>
    <div class="tab-pane fade" id="nav-how_is_it_made" role="tabpanel" aria-labelledby="nav-how_is_it_made-tab">...</div>
</div>
@endsection