routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes([
    'reset' => false,
    'confirm' => false,
    'verify' => false,
]);
Route::get('/logout', 'Auth\LoginController@logout')->name('get-logout');

Route::group([
    'middleware' => 'auth',
    'namespace' => 'Profile',
], function () {
    Route::get('/profile', 'ProfileController@index')->name('profile');
    Route::get('/profile/ads/{category}', 'ProfileController@user_ads_by_category')->name('user_ads_by_category');

    Route::resource('ads', 'AdController')->except(['index', 'show']);
});

Route::get('/', 'MainController@index')->name('index');
Route::get('/how_is_it_made', 'MainController@how_is_it_made')->name('how_is_it_made');
Route::get('/obyavlenie', 'MainController@ads')->name('ads');
Route::get('/obyavlenie/{category}', 'MainController@ads_by_category')->name('ads_by_category');
Route::get('/obyavlenie/{category}/{ad_id}', 'MainController@ad_id')->name('ad_id');
Route::get('/user_ads/{user_id}', 'MainController@user_ads')->name('user_ads');

resources/views/layouts/ad_card.blade.php
<div class="card border @if($ad->isTop()) border-warning @else border-info @endif mb-lg-3" style="width: 17rem;">
    @if($ad->isTop())
        <span class="badge badge-warning badge__urgently">ТОП</span>
    @endif
    <img class="card-img-top" src="{{Storage::url($ad->head_photo)}}" alt="Card image cap">
    <div class="card-body">
        <div class="d-flex">
            <h5 class="card-title mr-auto">{{$ad->title}}</h5>
            <i class="fa fa-bookmark-o fa-2x"></i>
        </div>
        <p class="card-text text-truncate" style="max-height: 50px;">{{$ad->description}}
            <br><small class="text-muted">Опубликовано в: {{$ad->created_at}}</small>
        </p>
        <a href="{{route('ad_id', [$ad->category->code, $ad])}}" class="stretched-link"></a>
    </div>
</div>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="css/main.css">
    <script src="{{ asset('js/main.js') }}"></script>
    <title>@yield('title')</title>

</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03"
                aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{{route('index')}}">StroyHub</a>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav mx-auto mt-2 mt-lg-0 w-100 nav-justified">
                <li class="nav-item">
                    <a class="nav-link" href="{{route('how_is_it_made')}}">Как это сделано?</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Лучшие работы</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{route('ads')}}">Обьявления</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{route('ads.create')}}">Добавить объявление</a>
                </li>
                @guest()
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('login')}}">Войти</a>
                    </li>
                @endguest
                @auth()
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('profile')}}">{{Auth::user()->name}}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('get-logout')}}">Выйти</a>
                    </li>
                @endauth
            </ul>
        </div>
    </nav>
    <!--Main functianlity-->
    @if(session()->has('success'))
        <p class="alert alert-success">{{ session()->get('success') }}</p>
    @elseif(session()->has('warning'))
        <p class="alert alert-warning">{{ session()->get('warning') }}</p>
    @endif
    @yield('content')

    <!--End of Main functianlity-->
    <footer id="footer" class="footer py-5">
        <div class="row justify-content-around">
            <div>
                <p><small>© 2020 ТОО "StroyHub" - все права защищены <br> По вопросам рекламы:
                        info@stroyhub.com</small></p>
                <img src="img/g1.png" alt="" style="width:150px;">
            </div>
            <div>
                <ul class="list-unstyled">
                    <li>
                        <a href="{{route('how_is_it_made')}}">Как это сделано?</a>
                    </li>
                    <li>
                        <a href="#">Лучшие работы</a>
                    </li>
                    <li>
                        <a href="{{route('ads')}}">Обьявления</a>
                    </li>
                    <li>
                        <a href="{{route('ads.create')}}">Добавить объявление</a>
                    </li>
                    <li>
                        <a href="#">Войти</a>
                    </li>
                </ul>
            </div>
            <div>
                <ul class="list-unstyled">
                    <li>
                        <a href="#!">Карта сайта</a>
                    </li>
                    <li>
                        <a href="#!">Связаться с администрацией</a>
                    </li>
                    <li>
                        <a href="#!">Пользовательское соглашение</a>
                    </li>
                    <li>
                        <a href="#!">Политика конфиденциальности</a>
                    </li>
                </ul>
            </div>
        </div>
    </footer>
</div>
</body>
</html>

resources/views/layouts/search_form.blade.php
<form class="form-inline my-2 my-lg-0">
    <div class="dropdown show">
        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            @if( isset($category))
                {{$category->name}}
            @else
                Все категорий
            @endif
        </a>

        <div class="dropdown-menu dropdown-multicol" aria-labelledby="dropdownMenuLink">
            <div class="dropdown">
                <a class="dropdown-item" href="{{route('ads_by_category', ['all_categories'])}}">Все категорий</a>
                @foreach($categories as $cat)
                    <a class="dropdown-item" href="{{route('ads_by_category', [$cat->code])}}">{{$cat->name}}</a>
                @endforeach
            </div>
        </div>
    </div>
    <div class="dropdown show px-2">
        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Все регионы
        </a>

        <div class="dropdown-menu dropdown-multicol" aria-labelledby="dropdownMenuLink">
            <div class="dropdown-row">
                <a class="dropdown-item" href="#">Oranges</a>
                <a class="dropdown-item" href="#">Bananas</a>
                <a class="dropdown-item" href="#">Apples</a>
            </div>
        </div>
    </div>
    <input class="form-control mr-sm-2 col-lg-6" type="search" placeholder="Поиск объявления" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
</form>